fastapi - login/out & forgot/reset password
jmcheon/matcha pull request #51
Opened 2024-10-07 19:18 UTC by jmcheon

## Login 
- [x] login
- [x] logout
- [x] refresh api

## Password
- [x] forget password
  - [x] send password reset email
- [x] reset password

2024-10-07 19:27 UTC, jmcheon commented
resolve #42

2024-10-07 23:24 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
> +    redirect_url = f'{FRONT_HOST}/{lang}/auth/reset-password'
NGINX_HOST로 바꿔주세요

2024-10-07 23:25 UTC, sungyongcho requested changes
코드 확인 해봤는데 reset password부분이 동작하고 있지 않네요
코드 확인 해봤는데 account 정보 업데이트 하는 부분이 없어서  이부분까지 구현이 필요합니다

그리고 디버깅용 print도 전부 지워주세요

2024-10-07 23:26 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
> +    print(data)
잘 동작하면 지워주세요

2024-10-07 23:26 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
>      print("register", data, lang)
잘 동작하면 지워주세요

2024-10-07 23:27 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
> +    print("logout():", accessToken)
잘 동작하면 지워주세요

2024-10-07 23:27 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
> +    print("refresh():", refreshToken)
잘 동작하면 지워주세요

2024-10-07 23:27 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
> +    print("forgot-password():", data, lang, email)
잘 동작하면 지워주세요

2024-10-07 23:27 UTC, sungyongcho commented on back-fastapi/src/controllers/auth_controller.py
> +    print("reset-password():", token, lang)
잘 동작하면 지워주세요

2024-10-09 16:05 UTC, sungyongcho approved these changes
LGTM

2024-10-09 16:07 UTC, merged